### ISSUE TITLE
messagebox cannot show button content

### ISSUE THREAD

**Issue by mzy666888** [MaSch0212/MaSch#1]
I use the control: MessageBox, but the button ok/cancel text not show?

![image](https://user-images.githubusercontent.com/2587129/112083359-d301ed80-8bc1-11eb-9181-5c12f5f6d3a5.png)

the code:
```MessageBox.Show("222", "title", MessageBoxButton.OKCancel, MessageBoxImage.Information);```

**Comment by MaSch0212** [comment]
Hi, for Styles and Translations to work in the WPF libraries you need to add the resource dictionary "ControlStyles.xaml" from Project "MaSch.Presentation.Wpf.Themes" to your app.xaml.
You can see an example of this here: https://github.com/MaSch0212/cura-manager/blob/cdf8632a92c7e157984a889ac5dad374a7ac8ecd/src/CuraManager/App.xaml#L13

You currently also need to add the "MaSch.Presentation.Wpf.Themes" NuGet package to your project in Version 0.1.3 in addition to the "Controls" one, because the dependency in that Controls package is currently using and older version of the Themes package (0.1.2) which contains a bug.

**Comment by MaSch0212** [comment]
Version 0.1.5 of MaSch.Presentation.Wpf.Controls is published that now uses the correct version of Themes, so an explicit reference to the Themes package is not necessary anymore ;)

**Comment by MaSch0212** [comment]
I guess this issue is resolved, so I will close it. If you got more issue, please let me know.
